// lib/manual/manual-data.ts
// Stars of Dominion — Complete 15-Section Manual Data

import type { ManualSection } from './types';

export const MANUAL_DATA: ManualSection[] = [
    {
        id: 'intro',
        title: 'Section 1: Introduction',
        icon: 'book',
        subsections: [
            {
                id: 'concept',
                title: 'Core Concept',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'Stars of Dominion is a real-time asynchronous grand strategy game. Unlike traditional RTS games, "real-time" here means calculations happen continuously on the server, but strategic updates (production, construction, research) trigger in 6-hour cycles called "Ticks".'
                    },
                    {
                        type: 'strategy_tip',
                        title: 'Commander\'s Role',
                        content: 'As an Empire Commander, you don\'t micromanage individual units. You set high-level doctrines, manage economic flows, and respond to crises. Your power comes from influence, reputation, and control of the galaxy\'s vital resources.'
                    }
                ]
            }
        ]
    },
    {
        id: 'loop',
        title: 'Section 2: Core Gameplay Loop',
        icon: 'repeat',
        subsections: [
            {
                id: 'expand',
                title: 'The Strategic Cycle',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'EXPAND: Claim neutral systems and survey anomalies.',
                            'DEVELOP: Build infrastructure and specialize planets.',
                            'INTERACT: Trade, spy, or negotiate with rivals.',
                            'RESPOND: Counter enemy sabotages and military incursions.',
                            'ADAPT: Re-evaluate doctrines as the galactic situation changes.'
                        ]
                    },
                    {
                        type: 'warning',
                        title: 'Event interruptions',
                        content: 'While Ticks are predictable, Crises (sabotage, blockade, invasion) are not. They open timed response windows that require immediate strategic decisions.'
                    }
                ]
            }
        ]
    },
    {
        id: 'economy',
        title: 'Section 3: Resources & Economy',
        icon: 'coins',
        subsections: [
            {
                id: 'trade_res',
                title: 'Trade Resources',
                blocks: [
                    {
                        type: 'table',
                        content: [
                            { resource: 'METALS', usage: 'Hull construction, infrastructure' },
                            { resource: 'CHEMICALS', usage: 'Fuel, ship systems, terraforming' },
                            { resource: 'FOOD', usage: 'Population growth, stability' },
                            { resource: 'AMMO', usage: 'Fleet readiness, planetary defense' },
                            { resource: 'RARES', usage: 'Advanced tech, high-end ship components' }
                        ]
                    }
                ]
            },
            {
                id: 'socio_econ',
                title: 'Socio-Economic Foundation',
                blocks: [
                    {
                        type: 'strategy_tip',
                        title: 'Energy as Capacity',
                        content: 'ENERGY is not a stockpile. It is a capacity vs upkeep system. Every building and service consumes a portion of your current Energy output. If consumption exceeds output, your empire enters a partial blackout, reducing all efficiency by 50%.'
                    },
                    {
                        type: 'paragraph',
                        content: 'CREDITS (local currency) are used for instant tasks, recruitment, and upkeep. HAPPINESS (stability) affects worker productivity and rebellion risk.'
                    }
                ]
            },
            {
                id: 'derived',
                title: 'Derived Outputs',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'MILITARY: Generated by bases, used for fleet maintenance.',
                            'RESEARCH: Generated by labs, used for tech progression.',
                            'CULTURAL: Generated by monuments, used for influence and council votes.'
                        ]
                    }
                ]
            }
        ]
    },
    {
        id: 'planets',
        title: 'Section 4: Planetary Development',
        icon: 'globe',
        subsections: [
            {
                id: 'specialization',
                title: 'Building & Specialization',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'Planets are the backbone of your power. Each planet has limited slots for buildings. Strategy revolves around specialization to maximize tile bonuses.'
                    },
                    {
                        type: 'table',
                        content: [
                            { type: 'Industrial', benefit: 'High Metal/Chemical output.' },
                            { type: 'Research', benefit: 'Core science generation.' },
                            { type: 'Agricultural', benefit: 'Food and massive population capacity.' },
                            { type: 'Fortress', benefit: 'High defense and military projection.' }
                        ]
                    },
                    {
                        type: 'warning',
                        title: 'Over-expansion',
                        content: 'Each planet adds an "Administrative Burden". Expanding too fast without stabilizing your core will lead to a Stability Collapse.'
                    }
                ]
            }
        ]
    },
    {
        id: 'military',
        title: 'Section 5: Military System',
        icon: 'sword',
        subsections: [
            {
                id: 'phases',
                title: 'Two-Phase Combat',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            '1. ORBITAL: Fleets clash for system control. Victory here allows bombardment or ground assault.',
                            '2. GROUND: Armies fight for planet possession. Requires orbital supremacy.'
                        ]
                    }
                ]
            },
            {
                id: 'units',
                title: 'Unit Counter System',
                blocks: [
                    {
                        type: 'table',
                        content: [
                            { unit: 'Infantry', counter: 'Airborne' },
                            { unit: 'Tanks', counter: 'Anti-Armor' },
                            { unit: 'Anti-Armor', counter: 'Infantry' },
                            { unit: 'Airborne', counter: 'Tanks' },
                            { unit: 'Special Ops', counter: 'Admirals/Generals (Assassination)' }
                        ]
                    },
                    {
                        type: 'strategy_tip',
                        title: 'Logistics',
                        content: 'Military operations require continuous AMMO and MANPOWER. A fleet without ammo deals only 10% damage and cannot use special abilities.'
                    }
                ]
            }
        ]
    },
    {
        id: 'leadership',
        title: 'Section 6: Leadership System',
        icon: 'users',
        subsections: [
            {
                id: 'leaders',
                title: 'Admirals, Generals, Governors',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'Leaders provide massive bonuses to fleets, armies, and planets. They gain XP through tasks and develop dynamic Traits over time.'
                    },
                    {
                        type: 'example',
                        title: 'Governor Loyalty',
                        content: 'A Governor with high Deception but low Loyalty might start skimming credits or, in extreme cases, hand the planet to a rival during a Crisis.'
                    }
                ]
            }
        ]
    },
    {
        id: 'doctrine',
        title: 'Section 7: Doctrine System',
        icon: 'shield',
        subsections: [
            {
                id: 'domains',
                title: 'Strategic Domains',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'Doctrines represent your empire\'s identity. You can have one active doctrine per domain: Military, Economic, Intelligence.'
                    },
                    {
                        type: 'warning',
                        title: 'Doctrine Switching',
                        content: 'Switching a doctrine triggers a 48-hour cooldown and a temporary reputation hit. Choose your identity wisely—it defines your bonuses and automated crisis responses.'
                    }
                ]
            }
        ]
    },
    {
        id: 'diplomacy',
        title: 'Section 8: Diplomacy & Reputation',
        icon: 'handshake',
        subsections: [
            {
                id: 'metrics',
                title: 'Reputation Metrics',
                blocks: [
                    {
                        type: 'table',
                        content: [
                            { metric: 'Aggression', effect: 'Affects threat level and alliance cost.' },
                            { metric: 'Reliability', effect: 'Affects lease success and trade trust.' },
                            { metric: 'Deception', effect: 'Affects espionage detection chance.' },
                            { metric: 'Trade Influence', effect: 'Affects market manipulation strength.' }
                        ]
                    },
                    {
                        type: 'paragraph',
                        content: 'Reputation is dynamic. Attacking an ally destroys Reliability, while successful trade improves Trade Influence.'
                    }
                ]
            }
        ]
    },
    {
        id: 'espionage',
        title: 'Section 9: Intelligence & Espionage',
        icon: 'eye',
        subsections: [
            {
                id: 'ops',
                title: 'Espionage Operations',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'Sabotage: Disable buildings or fleets for 24 hours.',
                            'Infiltration: Gain full visibility of a rival\'s economy.',
                            'Misinformation: Fake fleet movements to lure enemies away.',
                            'Inciting Rebellion: Lower a planet\'s happiness until a civil war breaks out.'
                        ]
                    },
                    {
                        type: 'formula',
                        title: 'Success Probability',
                        content: 'Success % = (Int Strength - Enemy Ops Def) * Logic Modifier + Leader Bonus'
                    }
                ]
            }
        ]
    },
    {
        id: 'crisis',
        title: 'Section 10: Crisis System (Core)',
        icon: 'alert-triangle',
        subsections: [
            {
                id: 'response',
                title: 'The Strategy Window',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'When an operation is launched against you, a Crisis Window opens. You do not know EXACTLY what the enemy chose, but you must respond.'
                    },
                    {
                        type: 'strategy_tip',
                        title: 'The Prediction Game',
                        content: 'If the Attacker predicts your response correctly (e.g. predicts you will "Fortify" and you do), their attack is 35% more effective. If they guess wrong, your defense gains a massive boost. This is a game of psychological reading.'
                    }
                ]
            }
        ]
    },
    {
        id: 'government',
        title: 'Section 11: Government & Society',
        icon: 'crown',
        subsections: [
            {
                id: 'ideology',
                title: 'The Spectrum of Power',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'CAPITALIST: Focus on market manipulation and trade.',
                            'SOCIALIST: Focus on stability and resource efficiency.',
                            'IMPERIAL: Focus on leadership control and construction speed.',
                            'TECHNOCRATIC: Focus on research and automation.',
                            'MILITARIST: Focus on fleet strength and orbital control.'
                        ]
                    },
                    {
                        type: 'warning',
                        title: 'Internal Factions',
                        content: 'Factions within your own society will pressure you to follow their interests. Ignoring them for too long leads to strikes or civil war.'
                    }
                ]
            }
        ]
    },
    {
        id: 'economic_war',
        title: 'Section 12: Economic Warfare',
        icon: 'trending-down',
        subsections: [
            {
                id: 'disruption',
                title: 'Weaponizing the Economy',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'Trade Disruption: Raiding hyperlanes to starve an enemy of specific resources.',
                            'Energy Collapse: Sabotaging core power plants during a battle.',
                            'Credit Destabilization: Flooding the market to devalue a rival\'s reserves.'
                        ]
                    }
                ]
            }
        ]
    },
    {
        id: 'collapse',
        title: 'Section 13: Collapse System',
        icon: 'shredder',
        subsections: [
            {
                id: 'triggers',
                title: 'Imperial Decay',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'Total defeat is rare. Usually, an empire "Collapses". This happens when stability reaches zero or debt becomes unpayable.'
                    },
                    {
                        type: 'strategy_tip',
                        title: 'Controlled Collapse',
                        content: 'Advanced players may trigger a "Controlled Collapse"—intentionally letting a rebellious frontier region break away to save the core empire\'s economic integrity.'
                    }
                ]
            }
        ]
    },
    {
        id: 'victory',
        title: 'Section 14: Victory Conditions',
        icon: 'trophy',
        subsections: [
            {
                id: 'paths',
                title: 'Galactic Dominance',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'CONQUEST: Control 60% of the strategic systems in the galaxy.',
                            'ENLIGHTENMENT: Complete the final "Post-Singularity" research tier and build the Great Archive.',
                            'ECONOMIC HEGEMONY: Control over 75% of total galactic trade volume.'
                        ]
                    }
                ]
            }
        ]
    },
    {
        id: 'beginner',
        title: 'Section 15: Beginner Strategy',
        icon: 'star',
        subsections: [
            {
                id: 'priorities',
                title: 'The First 48 Hours',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'Focus on ENERGY. You cannot build anything without a stable power grid.',
                            'Claim 3-5 systems early before rivals block you.',
                            'Assign Governors immediately—XP is precious.',
                            'Don\'t neglect AMMO. A large fleet without ammo is just a target.'
                        ]
                    },
                    {
                        type: 'example',
                        title: 'Common Mistake',
                        content: 'Building research labs on planets with high metal bonuses. Match your buildings to the planet\'s natural strengths!'
                    }
                ]
            }
        ]
    }
];
