// lib/manual/manual-data.ts
// Stars of Dominion — Complete 15-Section Manual Data

import type { ManualSection } from './types';

export const MANUAL_DATA: ManualSection[] = [
    {
        id: 'intro',
        title: 'Section 1: Introduction',
        icon: 'book',
        subsections: [
            {
                id: 'concept',
                title: 'Core Concept',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'Stars of Dominion is a real-time asynchronous grand strategy game. Unlike traditional RTS games, "real-time" here means calculations happen continuously on the server, but strategic updates (production, construction, research) trigger in 6-hour cycles called "Ticks".'
                    },
                    {
                        type: 'strategy_tip',
                        title: 'Commander\'s Role',
                        content: 'As an Empire Commander, you don\'t micromanage individual units. You set high-level doctrines, manage economic flows, and respond to crises. Your power comes from influence, reputation, and control of the galaxy\'s vital resources.'
                    }
                ]
            }
        ]
    },
    {
        id: 'loop',
        title: 'Section 2: Core Gameplay Loop',
        icon: 'repeat',
        subsections: [
            {
                id: 'expand',
                title: 'The Strategic Cycle',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'EXPAND: You start with one capital. Commission a fleet (capital → UNITS → Space tab — your capital\'s Orbital Shipyard lays corvettes and destroyers; cruisers need an Advanced Spaceyard or Fleet Drydock, battleships a Capital Spaceyard), then PING → SCAN → SURVEY unexplored systems from the system panel — a fleet in or next to the target is required for scans and surveys. A survey charts the system\'s worlds; unowned UNSETTLED ones can be settled for 20,000 credits + 1,000 metals + 1,000 food. Your own home system holds your first settlement targets.',
                            'DEVELOP: Build infrastructure and specialize planets.',
                            'INTERACT: Trade, spy, or negotiate with rivals.',
                            'RESPOND: Counter enemy sabotages and military incursions.',
                            'ADAPT: Re-evaluate doctrines as the galactic situation changes.'
                        ]
                    },
                    {
                        type: 'warning',
                        title: 'Event interruptions',
                        content: 'While Ticks are predictable, Crises (sabotage, blockade, invasion) are not. They open timed response windows that require immediate strategic decisions.'
                    }
                ]
            }
        ]
    },
    {
        id: 'economy',
        title: 'Section 3: Resources & Economy',
        icon: 'coins',
        subsections: [
            {
                id: 'trade_res',
                title: 'Trade Resources',
                blocks: [
                    {
                        type: 'table',
                        content: [
                            { resource: 'METALS', usage: 'Hull construction, infrastructure' },
                            { resource: 'CHEMICALS', usage: 'Fuel, ship systems, terraforming' },
                            { resource: 'FOOD', usage: 'Population growth, stability' },
                            { resource: 'AMMO', usage: 'Fleet readiness, planetary defense' },
                            { resource: 'RARES', usage: 'Advanced tech, high-end ship components' }
                        ]
                    }
                ]
            },
            {
                id: 'socio_econ',
                title: 'Socio-Economic Foundation',
                blocks: [
                    {
                        type: 'strategy_tip',
                        title: 'Energy as Capacity',
                        content: 'ENERGY is not a stockpile. It is a capacity vs upkeep system. Every building and service consumes a portion of your current Energy output. If consumption exceeds output, your empire enters a partial blackout, reducing all efficiency by 50%.'
                    },
                    {
                        type: 'paragraph',
                        content: 'CREDITS (local currency) are used for instant tasks, recruitment, and upkeep. HAPPINESS (stability) affects worker productivity and rebellion risk.'
                    }
                ]
            },
            {
                id: 'derived',
                title: 'Derived Outputs',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'MILITARY: Generated by bases, used for fleet maintenance.',
                            'RESEARCH: Generated by labs, used for tech progression.',
                            'CULTURAL: Generated by monuments, used for influence and council votes.'
                        ]
                    }
                ]
            }
        ]
    },
    {
        id: 'planets',
        title: 'Section 4: Planetary Development',
        icon: 'globe',
        subsections: [
            {
                id: 'specialization',
                title: 'Building & Specialization',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'Planets are the backbone of your power. Each planet has limited slots for buildings. Strategy revolves around specialization to maximize tile bonuses.'
                    },
                    {
                        type: 'table',
                        content: [
                            { type: 'Industrial', benefit: 'High Metal/Chemical output.' },
                            { type: 'Research', benefit: 'Core science generation.' },
                            { type: 'Agricultural', benefit: 'Food and massive population capacity.' },
                            { type: 'Fortress', benefit: 'High defense and military projection.' }
                        ]
                    },
                    {
                        type: 'warning',
                        title: 'Over-expansion',
                        content: 'Each planet adds an "Administrative Burden". Expanding too fast without stabilizing your core will lead to a Stability Collapse.'
                    }
                ]
            }
        ]
    },
    {
        id: 'military',
        title: 'Section 5: Military System',
        icon: 'sword',
        subsections: [
            {
                id: 'phases',
                title: 'Two-Phase Combat',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            '1. ORBITAL: Fleets clash for system control. Victory here allows bombardment or ground assault.',
                            '2. GROUND: Advanced planetary siege. Involves unit composition, tactical cycles, and morale attrition.'
                        ]
                    },
                    {
                        type: 'strategy_tip',
                        title: 'Orbital Superiority',
                        content: 'Bombardment is essential to strip enemy fortifications and suppress garrisons. Use "FORTIFICATION BOMBARDMENT" to reduce defense layers before landing your troops.'
                    }
                ]
            },
            {
                id: 'units',
                title: 'Ground Unit Roles',
                blocks: [
                    {
                        type: 'table',
                        content: [
                            { unit: 'INFANTRY', role: 'Foundation of any army. High morale, good all-rounder.' },
                            { unit: 'ARMOR', role: 'Punching through defenses. Strong vs Infantry, weak vs Anti-Armor.' },
                            { unit: 'ANTI_ARMOR', role: 'Specialized tank hunters. Essential for breaking armored pushes.' },
                            { unit: 'ARTILLERY', role: 'Support fire. High damage but fragile and supply-intensive.' },
                            { unit: 'SPECIAL_OPS', role: 'Disruption & Assassination. Can bypass frontlines to hit command bunkers.' }
                        ]
                    },
                    {
                        type: 'paragraph',
                        content: 'Recruiting units requires specific military infrastructure (Barracks and Foundries for ground units; a shipyard in the fleet\'s system for ships — bigger hulls need a bigger yard) and consumes MANPOWER and CREDITS in a real-time production queue.'
                    }
                ]
            },
            {
                id: 'siege_cycle',
                title: 'The Tactical Cycle',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'Ground combat is resolved in 4-tick "Tactical Cycles". Every 4 ticks, the simulation evaluates stances, calculates attrition, and reports losses.'
                    },
                    {
                        type: 'bullet_list',
                        content: [
                            'STANCE: Choose between Aggressive, Defensive, or Maneuver.',
                            'PREDICTION: Predict the enemy stance for a 35% effectiveness bonus.',
                            'RESOLUTION: At the end of the cycle, the clash is resolved based on Rock-Paper-Scissors modifiers.'
                        ]
                    }
                ]
            }
        ]
    },
    {
        id: 'leadership',
        title: 'Section 6: Leadership System',
        icon: 'users',
        subsections: [
            {
                id: 'leaders',
                title: 'Admirals, Generals, Governors',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'Leaders provide massive bonuses to fleets, armies, and planets. They gain XP through tasks and develop dynamic Traits over time.'
                    },
                    {
                        type: 'example',
                        title: 'Governor Loyalty',
                        content: 'A Governor with high Deception but low Loyalty might start skimming credits or, in extreme cases, hand the planet to a rival during a Crisis.'
                    }
                ]
            }
        ]
    },
    {
        id: 'doctrine',
        title: 'Section 7: Doctrine System',
        icon: 'shield',
        subsections: [
            {
                id: 'domains',
                title: 'Strategic Domains',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'Doctrines represent your empire\'s identity. You can have one active doctrine per domain: Military, Economic, Intelligence.'
                    },
                    {
                        type: 'warning',
                        title: 'Doctrine Switching',
                        content: 'Switching a doctrine triggers a 48-hour cooldown and a temporary reputation hit. Choose your identity wisely—it defines your bonuses and automated crisis responses.'
                    }
                ]
            }
        ]
    },
    {
        id: 'diplomacy',
        title: 'Section 8: Diplomacy & Reputation',
        icon: 'handshake',
        subsections: [
            {
                id: 'metrics',
                title: 'Reputation Metrics',
                blocks: [
                    {
                        type: 'table',
                        content: [
                            { metric: 'Aggression', effect: 'Affects threat level and alliance cost.' },
                            { metric: 'Reliability', effect: 'Affects lease success and trade trust.' },
                            { metric: 'Deception', effect: 'Affects espionage detection chance.' },
                            { metric: 'Trade Influence', effect: 'Affects market manipulation strength.' }
                        ]
                    },
                    {
                        type: 'paragraph',
                        content: 'Reputation is dynamic. Attacking an ally destroys Reliability, while successful trade improves Trade Influence.'
                    }
                ]
            }
        ]
    },
    {
        id: 'espionage',
        title: 'Section 9: Intelligence & Espionage',
        icon: 'eye',
        subsections: [
            {
                id: 'agents',
                title: 'Agents and Networks',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'Everything covert lives on one page: Intelligence > Espionage. Recruit agents there with credits, then send each one to a system another empire holds.'
                    },
                    {
                        type: 'bullet_list',
                        content: [
                            'A deployed agent builds a network in that system. As it grows it reveals more: first a rumor of fleets, then their count and owner, then their full composition and orders.',
                            'A staffed network on foreign soil also raises your infiltration of the system\'s owner. Infiltration climbs through four stages: Recon Cell, Embedded Network, Deep Assets, Shadow Government.',
                            'Recall an agent and their network starts to fade. Agents rest briefly between assignments.',
                            'A free agent can also run an operation. Their traits shift the odds (Veterans help everything, Brutal agents help sabotage, Seducers political work, Economists economic warfare) and change how easily it is traced back to you (Ghosts are quiet, Brutal agents are not). Each operation costs them cover, more when they are caught, and an agent with no cover left is burned.'
                        ]
                    }
                ]
            },
            {
                id: 'ops',
                title: 'Operations, the Board and Reports',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'Operations: pick an empire, one of its systems, then an operation. Each costs Intel and credits and takes up one of your operation slots until it resolves.',
                            'Your infiltration of the target decides what you can run. Intelligence gathering is open from the start; disinformation and economic warfare open at Embedded Network, sabotage and black operations at Deep Assets, political warfare (coups, assassinations, election interference) at Shadow Government.',
                            'The odds shown are your side only. The target\'s counter-intelligence and internal security are subtracted when the operation resolves.',
                            'Economic warfare also needs the Black Market Operations technology.',
                            'The Board posts time-limited opportunities and threats. Seize them before they expire.',
                            'Reports carry a confidence estimate. A report can be outdated, incomplete, or planted by the other side.',
                            'When an operation resolves you are told how it went and whether you were caught, and an after-action entry stays in Reports for about two days. When your service catches a foreign operation against you, you hear about it too: a caught operation names its sponsor, a suspected one names who your service blames, with no proof.'
                        ]
                    },
                    {
                        type: 'bullet_list',
                        content: [
                            'Counter-intelligence (its own tab) is paid every hour in Intel. The service budget raises your counter-intelligence strength, which cuts every foreign operation\'s odds against you and makes their reports on you likelier to be planted. System coverage, on up to ten of your systems, makes operations there likelier to be traced. If you cannot pay the upkeep, none of it works.',
                            'Cases: when a foreign operation hits you and your service does not catch who sent it, a case opens on the Cases tab. Clues come in over time (faster with more counter-intelligence): what it took, who could afford it, whose ships were there, who has motive, what the press and your sources say, what prisoners say. Pin each clue to the empire you think it points at, then accuse one publicly, leak the story, or wait. Suspicion can be wrong, and a false flag is built to make it so. Accuse wrongly and you insult an innocent empire; the real culprit gets away.',
                            'False flags: a False Flag Raid can be dressed up as a third empire\'s work. The victim\'s file fills with planted evidence pointing at them, and the victim\'s anger goes their way. Frames work best on an empire that could plausibly have done it. AI services frame, hire foreign faces, open their own files, chase leads, and accuse, sometimes rightly, sometimes because they were fooled.',
                            'You work at most twelve files at once; beyond that the oldest file about mere snooping is shelved. Quiet spying that nobody noticed opens no file at all.',
                            'Lines of inquiry: on an open file you can pursue a lead for Intel (follow the money, pull the sensor logs, check the method, ask your sources inside an empire, press a prisoner, trace the operative). One at a time; it reports back after some hours with a finding, nothing, or a lie. Counter-intelligence makes leads cheaper and faster.',
                            'The grid beside each person of interest shows what your pins establish: motive (MO), means (ME) and opportunity (OP). When you accuse, you can also name a theory of why. Name the right reason as well as the right culprit and the case lands harder; name the wrong reason and the press mocks you, even if the culprit was right.',
                            'Every suspect has a dossier: their species and creed, how things stand between you and what has happened lately, how deep your own sources go inside them, and what your service has found out about them (their reach inside you, their tradecraft, prisoners who claim to work for them). The assessment line reads only the clues you pinned to them.',
                            'Agents have a species. Most recruits are your own people; about one in four is a foreigner, dearer to hire. A witness who sees your operative describes their species, so a foreign hire points the victim at the foreigner\'s homeworld instead of at you. A victim with good files may know the operative as a freelancer, and a captured hireling will say who paid them.',
                            'A compromised agent in your own service is a mole: it feeds your open case files to the very empire you are investigating. Counter-intelligence strength is how you find it.',
                            'Rebel cells: on a world where unrest, an unhappy interest group and a reputation for oppression add up to real grievance, the unhappiest people organise into a cell. It grows while the grievance lasts and fades if the world is made content. You only see the cells your service has found (Internal security, on the Counter-intel tab). A crackdown hits every cell on a world and finds some, for political capital; it also raises your reputation for oppression and that world\'s unrest, which is how the next cell recruits. Abroad, cells your networks or deep infiltration can see appear under Movements abroad on the Operations tab: pay them (arm them, or pay through a cutout so a captured member cannot name you) and they strike more often, with heists that pay you a cut; but every cycle and every strike leaves evidence, and an exposed sponsor answers for it. When a cell strikes your world, you get a case file on it, and one possible answer is that no foreign hand was behind it at all. On a cell\'s file you can turn an informant: they name members of that one cell, and where its money comes from (a cutout keeps the sponsor\'s name from them), and your next crackdown on that world knows where to look. Strong, armed cells break their sponsors\' agents out of prison and kill governors. A cell that lasts about a month of game time and grows strong comes into the open as a secession crisis on its world, answered on the Government page like any other; if it is not settled or suppressed it becomes a breakaway state, which a new player can take. AI governments crack down on cells at home as hard as their temperament runs. If you join late, you can lead a movement underground instead of a state: the game gives you a cell inside someone else\'s empire, and you play it from hiding (strike, lie low, send a sponsor\'s money back, and declare when it is old and strong enough). Nobody, not even the government hunting you, learns that a person leads it. If the movement wins, the state it becomes is yours. And if your own empire falls to a conqueror, you can go into hiding: with the people who would still follow you, on one of your lost worlds out on the edge, while the worlds still remember you (a conquered world forgets its old rulers after a while, and becomes simply part of the empire that holds it). In hiding, your people take jobs: a payroll ship, a detention block, a broadcast. You choose who goes and what they do at each turn; the odds are shown only as words, and what happens is real. Bigger jobs are planned: pick a real target nearby (one of the conqueror\'s worlds, or a warship resting in reach), send someone to watch it, buy gear with the movement\'s own money (cheaper at a black market), give each person a part and choose an approach. A stolen warship waits in a hidden dock until your movement has a state to sail for. Every job leaves something behind for the conqueror\'s investigators. Your people can be wounded, taken or killed on a job, and the dead do not come back; a choice that may cost someone says so, and names them, before you make it. Those who are taken may talk under questioning, and a prison break can bring them home. Loyalty that runs out can turn someone in secret. The right job can settle a companion\'s own unfinished business. If your conqueror is not a person, a named officer hunts you: every strike makes them look harder, their searches are real, and you will read about their work as it happens. You can go after them; someone will take their place.',
                            'A Counter-Intel Sweep audits one of your own systems: foreign networks found there are broken up and named, and every rival\'s infiltration of you drops. The owners of a broken network find out.'
                        ]
                    },
                    {
                        type: 'strategy_tip',
                        title: 'Being caught',
                        content: 'An operation resolves undetected, suspected, or exposed. Exposure costs you with the victim and opens a debate in their chamber. Running many operations in the same region makes each one easier to spot.'
                    }
                ]
            }
        ]
    },
    {
        id: 'crisis',
        title: 'Section 10: Crisis System (Core)',
        icon: 'alert-triangle',
        subsections: [
            {
                id: 'response',
                title: 'The Strategy Window',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'When an operation is launched against you, a Crisis Window opens. You do not know EXACTLY what the enemy chose, but you must respond.'
                    },
                    {
                        type: 'strategy_tip',
                        title: 'The Ground Siege Stance Game',
                        content: 'Aggressive beats Maneuver, Maneuver beats Defensive, and Defensive beats Aggressive. If you predict the enemy correctly AND have the winning stance, you will inflict massive losses while taking minimal damage.'
                    }
                ]
            }
        ]
    },
    {
        id: 'government',
        title: 'Section 11: Government & Society',
        icon: 'crown',
        subsections: [
            {
                id: 'ideology',
                title: 'The Spectrum of Power',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'CAPITALIST: Focus on market manipulation and trade.',
                            'SOCIALIST: Focus on stability and resource efficiency.',
                            'IMPERIAL: Focus on leadership control and construction speed.',
                            'TECHNOCRATIC: Focus on research and automation.',
                            'MILITARIST: Focus on fleet strength and orbital control.'
                        ]
                    },
                    {
                        type: 'warning',
                        title: 'Internal Factions',
                        content: 'Factions within your own society will pressure you to follow their interests. Ignoring them for too long leads to strikes or civil war.'
                    }
                ]
            }
        ]
    },
    {
        id: 'economic_war',
        title: 'Section 12: Economic Warfare',
        icon: 'trending-down',
        subsections: [
            {
                id: 'disruption',
                title: 'Weaponizing the Economy',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'Trade Disruption: Raiding hyperlanes to starve an enemy of specific resources.',
                            'Energy Collapse: Sabotaging core power plants during a battle.',
                            'Credit Destabilization: Flooding the market to devalue a rival\'s reserves.'
                        ]
                    }
                ]
            }
        ]
    },
    {
        id: 'collapse',
        title: 'Section 13: Collapse System',
        icon: 'shredder',
        subsections: [
            {
                id: 'triggers',
                title: 'Imperial Decay',
                blocks: [
                    {
                        type: 'paragraph',
                        content: 'Total defeat is rare. Usually, an empire "Collapses". This happens when stability reaches zero or debt becomes unpayable.'
                    },
                    {
                        type: 'strategy_tip',
                        title: 'Controlled Collapse',
                        content: 'Advanced players may trigger a "Controlled Collapse"—intentionally letting a rebellious frontier region break away to save the core empire\'s economic integrity.'
                    }
                ]
            }
        ]
    },
    {
        id: 'victory',
        title: 'Section 14: Victory Conditions',
        icon: 'trophy',
        subsections: [
            {
                id: 'paths',
                title: 'Galactic Dominance',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'CONQUEST: Control 60% of the strategic systems in the galaxy.',
                            'ENLIGHTENMENT: Govern so well that nobody wants to leave: high approval, legitimacy and cohesion, no interest group dominant or neglected, at least three worlds, and a Great Archive standing (about three real days to build). Hold it for about three real days to begin Transcendence (slipping drains progress rather than erasing it), then one more day through a window the whole galaxy is told about, while every rival service works against you and may burn the Archive. Progress is on the SAGA tab.',
                            'ECONOMIC HEGEMONY: Control over 75% of total galactic trade volume.'
                        ]
                    }
                ]
            }
        ]
    },
    {
        id: 'beginner',
        title: 'Section 15: Beginner Strategy',
        icon: 'star',
        subsections: [
            {
                id: 'priorities',
                title: 'The First 48 Hours',
                blocks: [
                    {
                        type: 'bullet_list',
                        content: [
                            'Focus on ENERGY. You cannot build anything without a stable power grid.',
                            'Claim 3-5 systems early before rivals block you.',
                            'Assign Governors immediately—XP is precious.',
                            'Don\'t neglect AMMO. A large fleet without ammo is just a target.'
                        ]
                    },
                    {
                        type: 'example',
                        title: 'Common Mistake',
                        content: 'Building research labs on planets with high metal bonuses. Match your buildings to the planet\'s natural strengths!'
                    }
                ]
            }
        ]
    }
];
