import { InfluenceProfile } from './cold-war-types';

/**
 * Environmental context required to calculate incoming foreign influence on a system.
 */
export interface InfluenceContext {
    activePropagandaModifiers: Record<string, number>; // empireId -> additional pressure (0-50) from campaigns
    tradeVolumeWithEmpire: Record<string, number>;     // empireId -> relative standard trade volume
    distanceFromEmpireCore: Record<string, number>;    // empireId -> hyperspace jumps away
}

/**
 * Evaluates a single tick of soft-power influence pressure applied to a given system.
 * Modifies the profile in place and returns it.
 * This should be executed via Lazy Evaluation (e.g. only every X ticks or when explicitly viewed)
 * rather than strictly every micro-tick, to save performance on 150+ systems.
 */
export function updateSystemInfluence(
    profile: InfluenceProfile,
    context: InfluenceContext
): InfluenceProfile {
    const updatedInfluence = { ...profile.foreignInfluence };

    // 1. Gather all empires attempting to project power
    const attemptingEmpires = new Set([
        ...Object.keys(context.activePropagandaModifiers),
        ...Object.keys(context.tradeVolumeWithEmpire),
        ...Object.keys(context.distanceFromEmpireCore)
    ]);

    for (const empId of attemptingEmpires) {
        // Base natural pressure is generated by sheer proximity
        const jumps = context.distanceFromEmpireCore[empId] ?? 99; // 99 means essentially no pressure
        let pressure = 0;

        if (jumps <= 2) pressure += 15;
        else if (jumps <= 5) pressure += 5;

        // Trade is the primary peacetime vector for soft power
        const trade = context.tradeVolumeWithEmpire[empId] ?? 0;
        if (trade > 500) pressure += 20;
        else if (trade > 100) pressure += 10;

        // Propaganda provides massive, targeted burst pressure
        const propaganda = context.activePropagandaModifiers[empId] ?? 0;
        pressure += propaganda;

        // Apply resistance buffer. A high resistance (e.g. 80) blocks a lot of soft power.
        // A resistance of 0 allows rapid indoctrination.
        const effectivePressure = Math.max(0, pressure - (profile.resistance * 0.5));

        // Softly integrate the pressure into the persistent influence score
        const currentScore = updatedInfluence[empId] || 0;

        // Influence slowly drifts towards the sustained pressure value
        // Limit the shift to max 2 points per evaluation to make it read naturally over time
        const diff = effectivePressure - currentScore;
        const boundedShift = Math.max(-2, Math.min(2, diff * 0.1));

        updatedInfluence[empId] = clampScore(currentScore + boundedShift);
    }

    // Natural decay for empires that stopped applying pressure
    for (const empId in updatedInfluence) {
        if (!attemptingEmpires.has(empId)) {
            updatedInfluence[empId] = clampScore(updatedInfluence[empId] - 1);
            if (updatedInfluence[empId] === 0) {
                delete updatedInfluence[empId];
            }
        }
    }

    return {
        ...profile,
        foreignInfluence: updatedInfluence
    };
}

function clampScore(val: number): number {
    return Math.max(0, Math.min(100, Math.round(val)));
}
